----1)-----
-- Create table
CREATE TABLE Test_proc (
    Id INT,
    Name VARCHAR(100)
);

-- Create procedure
CREATE OR REPLACE PROCEDURE Insert_test(p_id INT, p_name VARCHAR)
LANGUAGE plpgsql
AS $$
BEGIN
    INSERT INTO Test_proc (Id, Name) VALUES (p_id, p_name);
END;
$$;

-- Call procedure
CALL Insert_test(2, 'Vikram');

-- Check inserted data
SELECT * FROM Test_proc;

----2)-----
CREATE TABLE EMPLOYEES (
EMPID SERIAL PRIMARY KEY,
EMPNAME VARCHAR(100),
DEPT VARCHAR(100),
SALARY INT
)

CREATE OR REPLACE PROCEDURE ADDEMPLOYEE(p_name VARCHAR,p_dept VARCHAR,p_salary INT)
Language plpgsql
AS $$
BEGIN 

INSERT INTO EMPLOYEES (EMPNAME,DEPT,SALARY)
VALUES (p_name,p_dept,p_salary);
END;
$$

--call it
CALL ADDEMPLOYEE ('Arjun', 'IT', 60000);
CALL ADDEMPLOYEE ('Vikram', 'Finance', 75000)

--verify 
Select * from EMPLOYEES

----3)-----
CREATE TABLE EMPLOYEES (
EMPID SERIAL PRIMARY KEY,
EMPNAME VARCHAR(100),
DEPT VARCHAR(100),
SALARY INT
)


CREATE OR REPLACE PROCEDURE UPDATESALARY(P_EMPID INT,P_INCREMENT INT)
LANGUAGE PLPGSQL
AS $$
BEGIN 
IF P_INCREMENT <=0 THEN RAISE NOTICE 'INCREMENT MUST BE GREATER THAN 0';
ELSE
UPDATE EMPLOYEES
SET SALARY =SALARY + P_INCREMENT
WHERE EMPID=P_EMPID;
END IF;
END;
$$;

--CALL IT
CALL UPDATESALARY(1,-1000);
Select * from EMPLOYEES


